version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: "./Dockerfile"

    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
        - ./data:/data/mongo

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - flask
